version: '3.8'

services:
  mcportfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8081"
    volumes:
      - ./mcportfoliooptimizer:/app/mcportfoliooptimizer
      - ./examples:/app/examples
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped 