name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Setup virtual environment and install dependencies
      run: |
        uv venv
        . .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Run Ruff checks
      run: |
        uv run ruff check .

    - name: Test build
      run: |
        . .venv/bin/activate
        uv pip install build
        python -m build
