name: codecov

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codecov:
    name: py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg # https://github.com/orgs/community/discussions/26434
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4  # Update from v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Setup virtual environment and install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"
          uv pip install ecos pytest pytest-cov

      - name: Generate coverage report
        run: |
          uv run pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4  # Update from v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true